### ISSUE TITLE
Update branches.md to outline naming conventions 

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/developer-manual#5]
## Renaming the main branch

Git defaults to naming the main branch as ‘master’. As the internet engineering task force outline, master-slave naming is oppressive language and not in line with Snook's values.

IETF suggest a list of alternative and inclusive naming conventions that can be used.
https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1

This can be set as a default on all developer machines with the command:

`git config --global init.defaultBranch main`

We should also include this in the [branches guide](https://github.com/WeAreSnook/developer-manual/blob/main/branches.md)

## Development branch?

In previous projects we maintained a `development` or `dev` branch alongside `main`. Dev acted as an integration branch to stage new features before releasing to `main`. I'm wondering whether we should carry this forwards or drop it as a practice.

It is based on the [gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

### Pros

- Allows us to separate work that is in production from in active development (although maybe that is what staging is for?)
- Allows us to bundle up work into releases and use git tag functionality to version our releases.

### Cons

- Delay in deploying features and sort of antithetical to the continuous integration approach.
- More branches to maintain.

@tosbourn would be interested to hear your thoughts on this.

**Comment by tosbourn** [comment]
In my personal experience `dev` branches are mainly useful when we have long/slow release processes. e.g if we need manual QA on things. Because developers can keep working at pace even if staging sign-off is slow.

Most of our projects warrant fast feedback loops, with lots of deploys going to staging for faster sign off. In this case `main` is more than enough and `dev` gets in the way. 

The one thing we def lose is bundling up work into releases (as you rightly point out). When releases/versions are required, this is way easier to do with `dev`/`main`. In practice I've rarely seen versioning in this way to be that useful. It depends on the project and we can always do project specific things when needed.

That was a lot of words to say "imo ditch `dev`".

`master` vs `main` - no question we should just use `main`. The decision to use `master` on DCMS was bourn from multiple questions around who was going to host the code and the project and the knowledge this would likely change very last minute. It felt like switching to `main` might break a workflow if moving between different version control systems / hosting environments / etc. Now things have stabilised we should update that project (I will create a ticket now)

**Comment by mathewtrivett** [comment]
Thanks for the feedback @tosbourn perhaps we could document the default way is main + feature branches unless the project meets certain requirements where versioning is required. e.g. where we are maintaining multiple versions etc.
